name: blog_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.2
  cloud_firestore: ^3.4.8
  firebase_auth: ^3.9.0
  firebase_core: ^1.22.0
  firebase_messaging: ^13.0.3
  firebase_storage: ^10.3.8
  flutter:
    sdk: flutter
  flutter_local_notifications: ^11.0.0
  get_it: ^7.2.0
  google_sign_in: ^5.4.1
  http: ^0.13.5
  image_picker: ^0.8.5+3
  stacked: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
