// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEtlXm7PYsYRAIbmjY9CrS5JDJj0OOLyM',
    appId: '1:225883828586:web:38d9f7f7ca7876c28d3513',
    messagingSenderId: '225883828586',
    projectId: 'blog-app-610fe',
    authDomain: 'blog-app-610fe.firebaseapp.com',
    storageBucket: 'blog-app-610fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGFMWbo9tjI5lqZRgM_HUHKlH6XU84BLY',
    appId: '1:225883828586:android:ca1a756136e85db38d3513',
    messagingSenderId: '225883828586',
    projectId: 'blog-app-610fe',
    storageBucket: 'blog-app-610fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF-QlD0Kp7sU8OEDpUWfoBp5pJdGOHPBA',
    appId: '1:225883828586:ios:f99c3cba51909a508d3513',
    messagingSenderId: '225883828586',
    projectId: 'blog-app-610fe',
    storageBucket: 'blog-app-610fe.appspot.com',
    iosClientId: '225883828586-968rq5s0pc83uhd0f6tto5sn99s6u79o.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF-QlD0Kp7sU8OEDpUWfoBp5pJdGOHPBA',
    appId: '1:225883828586:ios:f99c3cba51909a508d3513',
    messagingSenderId: '225883828586',
    projectId: 'blog-app-610fe',
    storageBucket: 'blog-app-610fe.appspot.com',
    iosClientId: '225883828586-968rq5s0pc83uhd0f6tto5sn99s6u79o.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogApp',
  );
}
